version: "3.9"

services:
  jupyter:
    image: python:3.12
    container_name: statistics_lab
    working_dir: /workspace
    volumes:
      - .:/workspace
      - pip-cache:/root/.cache/pip
    ports:
      - "8890:8888"
    environment:
      JUPYTER_TOKEN: statystyka2025
    command: >
      sh -c "
      pip install --no-cache-dir jupyterlab &&
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --LabApp.token='statystyka2025'
      "
volumes:
  pip-cache:
